### ISSUE TITLE
imageresponsive how to fire resize event?

### ISSUE THREAD

**Issue by adampotocki** [eddyystop/mithril-components#1]
How would i go about firing an on resize event in order to make images responsive?

**Comment by eddyystop** [comment]
picture.js (in public/js/vendor or https://github.com/scottjehl/picturefill) responds to browser resize events. So it'll take care of changing the image when the user manually resizes the browser.

You can fire resize programmatically with

```
var event = new Event('resize');
elem.dispatchEvent(event);
```

**Comment by adampotocki** [comment]
Thank you I wanted to resize on the fly (i think it's pointless) I'd have
to destroy current then reload new image...any graceful way of doing that?

**Comment by eddyystop** [comment]
picturefill replaces images itself e.g. `picImg.src = bestCandidate.url;` so you'd be no worse off doing that yourself. The browser caches the images so performance should be fine.

```
function changeImg(el, path, file) {
  el.src = path + file;
}
changeImg(document.getElementById('myImage'), '//http:.../', 'small.jpg');
```

**Comment by adampotocki** [comment]
gotcha thanks!
