### ISSUE TITLE
Not exactly issue, looking about How to

### ISSUE THREAD

**Issue by rainbow99984** [eddyystop/mithril-components#11]
Hi, Is there any jsfiddle / example available? or any how to, I see how to install but the js/css files are not available as download to experiment with.
Thanks.

**Comment by eddyystop** [comment]
Hi. Each component has a readme which contains sample code.

The Running Examples section in the repo's readme explains how to run the examples. You can play around with the components by cloning the repo.

**Comment by rainbow99984** [comment]
Thanks, I was looking at the wrong place.
