### ISSUE TITLE
NPM support

### ISSUE THREAD

**Issue by jsguy** [eddyystop/mithril-components#12]
Hi @eddyystop,

I'm the author of [misojs](http://misojs.com), (an isomorphic framework using mithril), and I was working on creating components that can be loaded via NPM, but there is no reason these cannot work with mithril as well - here is an example component that can be installed via NPM, and works with misojs:

https://github.com/jsguy/misojs-codemirror-component

As you know, NPM uses "require", so we need to somehow cater for that.

I was hoping that we could work together to make this work, instead of me creating my own version of something very similar to what you have already worked on here.

What are your thoughts?

**Comment by eddyystop** [comment]
I stopped using Mithril as I didn't find it very component-friendly back in the day. I haven't paid much attention to its recent major improvements in this area.

**Comment by jsguy** [comment]
Ok, fair enough - I'll see if I can come up with something :)
