### ISSUE TITLE
Auto-generated API docs

### ISSUE THREAD

**Issue by Satyam** [eddyystop/mithril-components#6]
Not sure if it is worth it, I added API docs comments to Datatable and produced the API docs for them.  Check them out.  Download the zip from https://github.com/Satyam/mithril-components/tree/APIDocs and expand the `api` folder.  

The initial view is not particularly exciting because there is just one module with doc-comments added but if all components had them, there would be one entry in `modules` for each.

If you go to the `controller` it won't show much, the constructor (the `controller` method itself)  and the `view` method.  However, if you check the `private` checkbox in the upper-right hand corner of the page, you can see the description for all the auxiliary methods and properties.

Is it worth it?

**Comment by eddyystop** [comment]
I love such docs on larger projects. I think they would become useful as our collection grew, as Mithril gained popularity, and more people used the collection. 

Perhaps it comes down to how easy it is to gen the docs. Generators I've used have been painful. I never used YUI's as I wasn't sure what was involved in getting it going.

Anyway this is relevant to me as I was planning to redo all my docs this weekend. So what would I have to install on my Windows laptop? (My Linux/Windows box is 1.5 weeks away.)

**Comment by Satyam** [comment]
If you have nodejs installed, it is just a matter of doing "sudo npm
install -g yuidocjs".  Well, in Windows you wouldn't do the "sudo" part.

Then, to run it, you just do "yuidoc ." in the project directory (where
the yuidoc.json file is or "yuidoc /myProject/" from elsewhere) and it
will redo the docs.

The tags are described in:  http://yui.github.io/yuidoc/syntax/index.html

Satyam

**Comment by eddyystop** [comment]
I'll play around with that. 
I just want to confirm you haven't pushed your API decoration in Datatable.js to the repo yet, as I don't see it there. I can use your fork as an example.

**Comment by Satyam** [comment]
I didn't because I'm not sure about it.   Does it look worth it? 

The problem is that with this Mithril anomaly of the controller being a
class but not quite, the docs look funny.  The controller gets a first
rate placement while the view becomes just a method.    

I know JSDoc is a more flexible thing and it could probably be tailored
to deal with this, but the problem is that it always have to be tailored
from the very start.  As it comes out of the box, it doesn't recognize
Markdown syntax and the styling is awful.  Like you have to start
downloading extras and extra styles just to get started.  Since it has
more tags than YUIdoc has, I am sure controllers and view could be
documented in a way that look equally important.

I also think that with the appropriate extras, the user guide could be
included.  As it is, YUI Doc is meant for API docs.  The YUI site has
User Guides and API docs separate, done with different tools.

Finally, GITHUB shows the readme files straight away, not so with
whatever these documenters do.

So, that is why I didn't send a pull request.  I am not sure about the
whole deal.  In fact, I am working on row selection on another branch
which does not have the doc-comments in it.  That is the measure of how
unsure I am.

Satyam

**Comment by eddyystop** [comment]
I have not had happy experiences with JSDoc. I suggest we stay with the readme's for now.
